### ISSUE TITLE
Footer does not scale down on mobile

### ISSUE THREAD

**Issue by jamesbeegen** [jamesbeegen/azziTowing#43]
Can someone look into this - the bottom of the footer gets cut off

@samuelberhe 
@Shahzor1998 
@alexelson1

**Comment by Shahzor1998** [comment]
Where specifically do you see this because I checked the base and I dont see any issue. I dont seee it in admin page but really we dont need it there since the owner is gonna use it there anyways.

**Comment by jamesbeegen** [comment]
I removed links from footer and it is fine now - we don't really need the links in the footer since the navbar is sticky and is always visible
